# Site settings
title: "/dev/null"
email: luqmanrom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http//:luqmanrom.github.io" # the base hostname & protocol for your site
twitter_username: luqmanrom
github_username:  luqmanrom

# Build settings
markdown: kramdown
